# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'IntrepidSwiftWisdom', :git => 'git@github.com:IntrepidPursuits/swift-wisdom.git'

target 'AnimationClub4' do

end

